### ISSUE TITLE
Discover store plugin no longer working on Steam Deck

### ISSUE THREAD

**Issue by midnightcatwalk** [tazihad/mount-Iso-Service-Dolphin-File-Manager#3]
On latest Stable OS, the option to mount/unmount a disc has disappeared from the right-click menu. 

Apologies if this is not the right place to leave this comment.

**Comment by tazihad** [comment]
@midnightcatwalk maybe steamdeck stopped showing dolphin service menu in Discover. 
Search from Dolphin file manager(Download new service) if it's available.  

![preferences-context-menu](https://github.com/tazihad/mount-Iso-Service-Dolphin-File-Manager/assets/19417232/394bede8-d637-4c94-a87b-34ab6f4a32d7)
